// Fix Guidance Knowledge Base (PRD §10). One entry per vuln type key.
// A CI test asserts every type the engine can emit has a guide here.

export const FIX_GUIDES = {
  sqli: {
    what: 'User input was concatenated directly into a SQL query.',
    why: 'Attacker can read, modify, or delete your entire database.',
    steps: [
      'Replace all string-concatenated queries with parameterized queries / prepared statements.',
      'Use an ORM (Sequelize, Prisma, Hibernate, SQLAlchemy) that parameterizes by default.',
      'Apply principle of least privilege to your database user.',
    ],
    before: `const q = "SELECT * FROM users WHERE id = " + req.params.id;`,
    after: `const q = "SELECT * FROM users WHERE id = ?";\ndb.execute(q, [req.params.id]);`,
    verify: 'Re-run SmartFuzz. SQLi should no longer appear.',
    ref: 'https://owasp.org/www-community/attacks/SQL_Injection',
  },
  xss: {
    what: 'User-supplied input was rendered in HTML without escaping.',
    why: 'Attacker can steal session cookies, redirect users, or deface the page.',
    steps: [
      'Encode all user input before rendering in HTML (context-appropriate encoding).',
      'Use a templating engine that auto-escapes (React JSX, Handlebars, Jinja2).',
      'Add a Content-Security-Policy header to limit script execution.',
    ],
    before: `<p>Results for: <%= req.query.q %></p>`,
    after: `<p>Results for: <%= encodeURIComponent(req.query.q) %></p>`,
    verify: 'Re-run SmartFuzz. XSS should no longer appear.',
    ref: 'https://owasp.org/www-community/attacks/xss/',
  },
  path_traversal: {
    what: 'A file path parameter was not validated, allowing traversal outside the webroot.',
    why: 'Attacker can read /etc/passwd, .env files, source code, or SSH keys.',
    steps: [
      'Resolve the full absolute path and verify it starts with the allowed base directory.',
      'Use an allowlist of permitted file names or paths.',
      'Never expose raw filesystem paths as parameters.',
    ],
    before: `res.sendFile('/var/www/' + req.query.file);`,
    after: `const base = '/var/www/uploads/';\nconst req_path = path.resolve(base, req.query.file);\nif (!req_path.startsWith(base)) return res.status(403).send('Forbidden');\nres.sendFile(req_path);`,
    verify: 'Re-run SmartFuzz. Path traversal should no longer appear.',
    ref: 'https://owasp.org/www-community/attacks/Path_Traversal',
  },
  cmd_injection: {
    what: 'User input was passed directly to a system shell command.',
    why: 'Attacker can execute any OS command on your server.',
    steps: [
      'Never pass user input to exec(), system(), shell_exec(), or child_process.exec().',
      'Use child_process.execFile() with argument arrays (no shell interpolation).',
      'Use allowlists — only permit specific pre-approved values.',
    ],
    before: `exec('ping ' + req.query.host, callback);`,
    after: `const allowed = ['google.com', 'example.com'];\nif (!allowed.includes(req.query.host)) return res.status(400).send('Invalid');\nexecFile('ping', ['-c', '1', req.query.host], callback);`,
    verify: 'Re-run SmartFuzz. Command injection should no longer appear.',
    ref: 'https://owasp.org/www-community/attacks/Command_Injection',
  },
  ssti: {
    what: 'User input was embedded in a server-side template without sanitization.',
    why: 'Template injection can escalate to remote code execution.',
    steps: [
      'Never pass user input directly into template rendering functions.',
      'Use a sandboxed template engine or disable dangerous template features.',
      'Validate and sanitize all input before use in templates.',
    ],
    before: `res.render('page', { content: req.query.content });`,
    after: `const safe = sanitize(req.query.content);\nres.render('page', { content: safe });`,
    verify: 'Re-run SmartFuzz. SSTI should no longer appear.',
    ref: 'https://owasp.org/www-community/attacks/Server-Side_Template_Injection',
  },
  open_redirect: {
    what: 'A redirect parameter was not validated, allowing redirection to external sites.',
    why: 'Attackers can use your domain to redirect users to phishing sites.',
    steps: [
      'Validate redirect URLs against an allowlist of permitted destinations.',
      'Use relative paths instead of full URLs for internal redirects.',
      'Reject any redirect target that is not on your own domain.',
    ],
    before: `res.redirect(req.query.next);`,
    after: `const allowed = ['/dashboard', '/profile'];\nif (!allowed.includes(req.query.next)) return res.redirect('/');\nres.redirect(req.query.next);`,
    verify: 'Re-run SmartFuzz. Open redirect should no longer appear.',
    ref: 'https://owasp.org/www-community/attacks/Unvalidated_Redirects_and_Forwards_Cheat_Sheet',
  },
  ssrf: {
    what: 'User-supplied URLs were fetched server-side without validation.',
    why: 'Attacker can probe internal services, cloud metadata endpoints, or exfiltrate data.',
    steps: [
      'Validate and allowlist permitted URL schemes and hosts.',
      'Block requests to private/reserved IP ranges (RFC1918, loopback, link-local).',
      'Use a dedicated HTTP client with SSRF protections (e.g. SmartFuzz\'s urlGuard).',
    ],
    before: `const data = await fetch(req.query.url);`,
    after: `await assertSafeUrl(req.query.url); // rejects private ranges\nconst data = await fetch(req.query.url);`,
    verify: 'Re-run SmartFuzz. SSRF should no longer appear.',
    ref: 'https://owasp.org/www-community/attacks/Server_Side_Request_Forgery',
  },
  idor: {
    what: 'Object IDs in URLs/parameters were not checked for authorization.',
    why: 'Any user can access or modify another user\'s data by changing the ID.',
    steps: [
      'Always verify the authenticated user owns the requested resource.',
      'Use indirect references (UUIDs, slugs) instead of sequential IDs.',
      'Apply row-level security in your database or ORM.',
    ],
    before: `const item = await Item.findById(req.params.id);`,
    after: `const item = await Item.findOne({ _id: req.params.id, userId: req.user.id });\nif (!item) return res.status(404).send('Not found');`,
    verify: 'Re-run SmartFuzz. IDOR should no longer appear.',
    ref: 'https://owasp.org/Top10/A01_2021-Broken_Access_Control/',
  },
  cors_misconfig: {
    what: 'The Access-Control-Allow-Origin header was set to wildcard (*) or reflected any origin.',
    why: 'Any website can make authenticated cross-origin requests to your API.',
    steps: [
      'Set Access-Control-Allow-Origin to a specific allowlisted origin, not *.',
      'Never reflect the Origin header without validation.',
      'Combine with SameSite=Strict cookies for defense in depth.',
    ],
    before: `res.header('Access-Control-Allow-Origin', '*');`,
    after: `const allowed = ['https://yourapp.com'];\nif (allowed.includes(req.headers.origin)) {\n  res.header('Access-Control-Allow-Origin', req.headers.origin);\n}`,
    verify: 'Re-run SmartFuzz. CORS misconfiguration should no longer appear.',
    ref: 'https://owasp.org/www-community/attacks/CORS_OriginHeaderScrutiny',
  },
  exposed_sensitive_file: {
    what: 'A sensitive file (.env, .git, backup) was publicly accessible.',
    why: 'Credentials, source code, or database dumps can be stolen.',
    steps: [
      'Block access to sensitive files in your web server config (nginx/Apache).',
      'Never deploy .env, .git, or backup files to the webroot.',
      'Use environment variables injected at runtime, not files in the repo.',
    ],
    before: `# .env in webroot — accessible at https://example.com/.env`,
    after: `# nginx: deny access\nlocation ~ /\\. { deny all; }\nlocation ~* \\.(env|git|sql|bak|zip)$ { deny all; }`,
    verify: 'Re-run SmartFuzz. Exposed file should no longer appear.',
    ref: 'https://owasp.org/Top10/A05_2021-Security_Misconfiguration/',
  },
  missing_security_header: {
    what: 'One or more security headers were missing from the HTTP response.',
    why: 'Missing headers enable XSS, clickjacking, and MIME-sniffing attacks.',
    steps: [
      'Add Content-Security-Policy, X-Frame-Options, and X-Content-Type-Options headers.',
      'Use a security middleware like helmet (Node.js) or SecurityHeaders.com for guidance.',
    ],
    before: `# No security headers`,
    after: `app.use(helmet()); // sets CSP, X-Frame-Options, X-Content-Type-Options, etc.`,
    verify: 'Re-run SmartFuzz. Missing header findings should no longer appear.',
    ref: 'https://owasp.org/www-project-secure-headers/',
  },
  insecure_cookie: {
    what: 'Session cookies were missing HttpOnly, Secure, or SameSite flags.',
    why: 'Cookies without HttpOnly can be stolen via XSS; without Secure they travel over HTTP.',
    steps: [
      'Set HttpOnly on all session cookies to prevent JavaScript access.',
      'Set Secure on all cookies when using HTTPS.',
      'Set SameSite=Strict or SameSite=Lax to prevent CSRF.',
    ],
    before: `res.cookie('session', token);`,
    after: `res.cookie('session', token, { httpOnly: true, secure: true, sameSite: 'strict' });`,
    verify: 'Re-run SmartFuzz. Insecure cookie findings should no longer appear.',
    ref: 'https://owasp.org/www-community/controls/SecureCookieAttribute',
  },
  no_https: {
    what: 'The application was served over cleartext HTTP.',
    why: 'All traffic including credentials can be intercepted by a network attacker.',
    steps: [
      'Obtain a TLS certificate (Let\'s Encrypt is free).',
      'Configure your web server to redirect HTTP to HTTPS.',
      'Add HSTS to prevent future HTTP connections.',
    ],
    before: `http://example.com`,
    after: `https://example.com (with HSTS)`,
    verify: 'Re-run SmartFuzz. HTTP finding should no longer appear.',
    ref: 'https://owasp.org/Top10/A02_2021-Cryptographic_Failures/',
  },
  missing_hsts: {
    what: 'The Strict-Transport-Security header was missing.',
    why: 'Without HSTS, browsers may connect over HTTP, enabling downgrade attacks.',
    steps: ['Add Strict-Transport-Security: max-age=31536000; includeSubDomains to all HTTPS responses.'],
    before: `# No HSTS header`,
    after: `Strict-Transport-Security: max-age=31536000; includeSubDomains`,
    verify: 'Re-run SmartFuzz. Missing HSTS should no longer appear.',
    ref: 'https://owasp.org/www-project-secure-headers/#http-strict-transport-security',
  },
  server_version_disclosure: {
    what: 'The server revealed its software version in response headers.',
    why: 'Version information helps attackers target known CVEs.',
    steps: [
      'Remove or obscure the Server and X-Powered-By headers.',
      'In nginx: server_tokens off; In Apache: ServerTokens Prod; ServerSignature Off.',
    ],
    before: `Server: Apache/2.4.49`,
    after: `Server: (hidden)`,
    verify: 'Re-run SmartFuzz. Version disclosure should no longer appear.',
    ref: 'https://owasp.org/www-project-secure-headers/',
  },
  info_disclosure: {
    what: 'The application leaked sensitive information (stack traces, internal IPs, emails).',
    why: 'Leaked information aids attackers in targeting the application.',
    steps: [
      'Disable detailed error messages in production (NODE_ENV=production).',
      'Log errors server-side; return generic messages to clients.',
      'Audit response bodies for internal IP addresses and email addresses.',
    ],
    before: `res.status(500).json({ error: err.stack });`,
    after: `res.status(500).json({ error: 'Internal server error' });`,
    verify: 'Re-run SmartFuzz. Information disclosure should no longer appear.',
    ref: 'https://owasp.org/www-community/Improper_Error_Handling',
  },
  default_credentials: {
    what: 'The application accepted default credentials (admin/admin, etc.).',
    why: 'Attackers routinely try default credentials as a first step.',
    steps: [
      'Change all default passwords immediately after deployment.',
      'Enforce strong password policies.',
      'Disable or remove default accounts that are not needed.',
    ],
    before: `admin / admin`,
    after: `Unique, strong credentials per deployment`,
    verify: 'Re-run SmartFuzz. Default credentials should no longer appear.',
    ref: 'https://owasp.org/Top10/A05_2021-Security_Misconfiguration/',
  },
  no_rate_limit_auth: {
    what: 'The login endpoint had no rate limiting or brute-force protection.',
    why: 'Attackers can try millions of password combinations automatically.',
    steps: [
      'Add rate limiting to login endpoints (e.g. express-rate-limit).',
      'Implement account lockout after N failed attempts.',
      'Consider CAPTCHA for repeated failures.',
    ],
    before: `router.post('/login', loginHandler);`,
    after: `router.post('/login', rateLimit({ windowMs: 15*60*1000, max: 10 }), loginHandler);`,
    verify: 'Re-run SmartFuzz. Rate limit finding should no longer appear.',
    ref: 'https://owasp.org/www-community/controls/Blocking_Brute_Force_Attacks',
  },
  csrf: {
    what: 'The application lacked CSRF protection on state-changing endpoints.',
    why: 'Attackers can trick authenticated users into performing unintended actions.',
    steps: [
      'Use CSRF tokens on all state-changing forms and API endpoints.',
      'Set SameSite=Strict on session cookies.',
      'Verify the Origin/Referer header on sensitive requests.',
    ],
    before: `<form action="/transfer" method="post">`,
    after: `<form action="/transfer" method="post">\n  <input type="hidden" name="_csrf" value="<%= csrfToken %>">`,
    verify: 'Re-run SmartFuzz. CSRF finding should no longer appear.',
    ref: 'https://owasp.org/www-community/attacks/csrf',
  },
  mass_assignment: {
    what: 'The application accepted unexpected fields in POST/PUT requests.',
    why: 'Attackers can set privileged fields like role=admin or isAdmin=true.',
    steps: [
      'Use an explicit allowlist of permitted fields when creating/updating records.',
      'Never pass req.body directly to a database model.',
    ],
    before: `User.create(req.body);`,
    after: `User.create({ name: req.body.name, email: req.body.email });`,
    verify: 'Re-run SmartFuzz. Mass assignment should no longer appear.',
    ref: 'https://owasp.org/www-community/vulnerabilities/Mass_Assignment_Cheat_Sheet',
  },
  parameter_tampering: {
    what: 'Business-logic parameters (price, quantity) were not validated server-side.',
    why: 'Attackers can manipulate prices, quantities, or other business values.',
    steps: [
      'Never trust client-supplied prices or business values.',
      'Always look up authoritative values from the database.',
      'Validate all numeric parameters against expected ranges.',
    ],
    before: `const total = req.body.price * req.body.qty;`,
    after: `const product = await Product.findById(req.body.productId);\nconst total = product.price * req.body.qty;`,
    verify: 'Re-run SmartFuzz. Parameter tampering should no longer appear.',
    ref: 'https://owasp.org/www-community/attacks/Web_Parameter_Tampering',
  },
  tech_fingerprint: {
    what: 'The technology stack was identifiable from response headers or page content.',
    why: 'Version information helps attackers target known CVEs.',
    steps: [
      'Remove or obscure version-revealing headers (Server, X-Powered-By, X-Generator).',
      'Remove generator meta tags from HTML.',
    ],
    before: `<meta name="generator" content="WordPress 5.8.1">`,
    after: `<!-- generator tag removed -->`,
    verify: 'Re-run SmartFuzz. Technology fingerprint should no longer appear.',
    ref: 'https://owasp.org/Top10/A06_2021-Vulnerable_and_Outdated_Components/',
  },
  known_cve: {
    what: 'A component with a known CVE was detected.',
    why: 'Known vulnerabilities have public exploits and are actively targeted.',
    steps: [
      'Update the affected component to a patched version.',
      'Check the CVE advisory for specific remediation guidance.',
      'Subscribe to security advisories for your dependencies.',
    ],
    before: `jquery@3.4.1 (vulnerable to CVE-2020-11022)`,
    after: `jquery@3.6.0 (patched)`,
    verify: 'Re-run SmartFuzz after updating. CVE finding should no longer appear.',
    ref: 'https://owasp.org/Top10/A06_2021-Vulnerable_and_Outdated_Components/',
  },
  nosql_injection: {
    what: 'User input was used in a NoSQL query without sanitization.',
    why: 'Attackers can bypass authentication or dump data using operator injection.',
    steps: [
      'Validate and sanitize all query parameters before use in database queries.',
      'Use schema validation (Mongoose, Joi) to reject unexpected operator objects.',
      'Never pass raw req.body/req.query directly to MongoDB queries.',
    ],
    before: `User.findOne({ username: req.body.username, password: req.body.password })`,
    after: `const { username, password } = z.object({ username: z.string(), password: z.string() }).parse(req.body);\nUser.findOne({ username, password })`,
    verify: 'Re-run SmartFuzz. NoSQL injection should no longer appear.',
    ref: 'https://owasp.org/www-community/attacks/NoSQL_Injection',
  },
  ldap_injection: {
    what: 'User input was embedded in an LDAP query without escaping.',
    why: 'Attackers can bypass authentication or enumerate directory entries.',
    steps: [
      'Escape all special LDAP characters in user input.',
      'Use parameterized LDAP queries if your library supports them.',
    ],
    before: `ldap.search('(uid=' + req.body.user + ')')`,
    after: `ldap.search('(uid=' + escapeLdap(req.body.user) + ')')`,
    verify: 'Re-run SmartFuzz. LDAP injection should no longer appear.',
    ref: 'https://owasp.org/www-community/attacks/LDAP_Injection',
  },
  xpath_injection: {
    what: 'User input was embedded in an XPath query without escaping.',
    why: 'Attackers can bypass authentication or extract XML data.',
    steps: [
      'Use parameterized XPath queries.',
      'Escape all special XPath characters in user input.',
    ],
    before: `xpath.select("//user[name='" + req.body.user + "']", doc)`,
    after: `xpath.select("//user[name=$name]", doc, { name: req.body.user })`,
    verify: 'Re-run SmartFuzz. XPath injection should no longer appear.',
    ref: 'https://owasp.org/www-community/attacks/XPATH_Injection',
  },
  auth_bypass: {
    what: 'Authentication was bypassed using SQL injection or other techniques.',
    why: 'Attackers gain unauthorized access to the application.',
    steps: [
      'Use parameterized queries for all authentication checks.',
      'Never concatenate user input into SQL queries.',
    ],
    before: `"SELECT * FROM users WHERE user='" + user + "' AND pass='" + pass + "'"`,
    after: `"SELECT * FROM users WHERE user=? AND pass=?", [user, pass]`,
    verify: 'Re-run SmartFuzz. Auth bypass should no longer appear.',
    ref: 'https://owasp.org/Top10/A07_2021-Identification_and_Authentication_Failures/',
  },
  weak_session_token: {
    what: 'Session tokens were short, predictable, or low-entropy.',
    why: 'Predictable tokens can be guessed, enabling session hijacking.',
    steps: [
      'Use cryptographically secure random token generation (crypto.randomBytes).',
      'Ensure tokens are at least 128 bits (16 bytes) of entropy.',
    ],
    before: `const token = Math.random().toString(36)`,
    after: `const token = crypto.randomBytes(32).toString('hex')`,
    verify: 'Re-run SmartFuzz. Weak session token should no longer appear.',
    ref: 'https://owasp.org/www-community/vulnerabilities/Insufficient_Session-ID_Length',
  },
  session_fixation: {
    what: 'The session ID was not regenerated after login.',
    why: 'Attackers can pre-set a session ID and hijack the session after login.',
    steps: [
      'Regenerate the session ID on every successful login.',
      'Invalidate the old session before creating a new one.',
    ],
    before: `// session ID unchanged after login`,
    after: `req.session.regenerate(() => { req.session.userId = user.id; });`,
    verify: 'Re-run SmartFuzz. Session fixation should no longer appear.',
    ref: 'https://owasp.org/www-community/attacks/Session_fixation',
  },
  missing_logout: {
    what: 'Session tokens remained valid after logout.',
    why: 'Stolen tokens can be replayed even after the user logs out.',
    steps: [
      'Invalidate the session server-side on logout (not just clear the cookie).',
      'Maintain a token blacklist or use short-lived tokens with refresh.',
    ],
    before: `res.clearCookie('session'); // token still valid server-side`,
    after: `await Session.deleteOne({ token }); res.clearCookie('session');`,
    verify: 'Re-run SmartFuzz. Missing logout should no longer appear.',
    ref: 'https://owasp.org/www-community/Session_Management_Cheat_Sheet',
  },
  no_rate_limit: {
    what: 'A sensitive endpoint had no rate limiting.',
    why: 'Enables brute force, enumeration, and denial-of-service attacks.',
    steps: [
      'Add rate limiting to all sensitive endpoints.',
      'Use express-rate-limit or a reverse proxy (nginx, Cloudflare) for rate limiting.',
    ],
    before: `router.post('/api/sensitive', handler);`,
    after: `router.post('/api/sensitive', rateLimit({ windowMs: 60000, max: 20 }), handler);`,
    verify: 'Re-run SmartFuzz. Rate limit finding should no longer appear.',
    ref: 'https://owasp.org/Top10/A09_2021-Security_Logging_and_Monitoring_Failures/',
  },
  directory_listing: {
    what: 'Directory listing was enabled, exposing file structure.',
    why: 'Attackers can enumerate files and find sensitive resources.',
    steps: [
      'Disable directory listing in your web server (nginx: autoindex off; Apache: Options -Indexes).',
    ],
    before: `autoindex on;`,
    after: `autoindex off;`,
    verify: 'Re-run SmartFuzz. Directory listing should no longer appear.',
    ref: 'https://owasp.org/www-community/Improper_Data_Validation',
  },
  exposed_admin_panel: {
    what: 'An admin panel was publicly accessible.',
    why: 'Admin interfaces are high-value targets for attackers.',
    steps: [
      'Restrict admin panel access by IP allowlist.',
      'Require strong authentication (MFA) for admin access.',
      'Move admin interfaces to a non-standard path or separate subdomain.',
    ],
    before: `# /admin accessible from any IP`,
    after: `# nginx: allow 10.0.0.0/8; deny all; (IP restriction)`,
    verify: 'Re-run SmartFuzz. Exposed admin panel should no longer appear.',
    ref: 'https://owasp.org/Top10/A05_2021-Security_Misconfiguration/',
  },
  predictable_resource: {
    what: 'Predictable resource locations (backup files, config files) were accessible.',
    why: 'Backup and config files often contain credentials or source code.',
    steps: [
      'Remove backup and config files from the webroot.',
      'Block access to common backup extensions (.bak, .sql, .zip) in your web server.',
    ],
    before: `# /backup.sql accessible`,
    after: `location ~* \\.(bak|sql|zip|tar|gz)$ { deny all; }`,
    verify: 'Re-run SmartFuzz. Predictable resource should no longer appear.',
    ref: 'https://owasp.org/Top10/A04_2021-Insecure_Design/',
  },
  verbose_error: {
    what: 'Detailed error messages (stack traces, DB errors) were returned to clients.',
    why: 'Error details help attackers understand the application internals.',
    steps: [
      'Set NODE_ENV=production to suppress stack traces.',
      'Return generic error messages to clients; log details server-side.',
    ],
    before: `res.status(500).json({ error: err.stack });`,
    after: `res.status(500).json({ error: 'Internal server error' });`,
    verify: 'Re-run SmartFuzz. Verbose error should no longer appear.',
    ref: 'https://owasp.org/www-community/Improper_Error_Handling',
  },
  forced_browsing: {
    what: 'Unlisted but accessible pages were found.',
    why: 'Hidden pages may contain sensitive functionality or data.',
    steps: [
      'Implement proper access controls on all pages, not just linked ones.',
      'Return 404 (not 403) for pages that should not be known to exist.',
    ],
    before: `# /admin/debug accessible without auth`,
    after: `router.get('/admin/debug', requireAuth, requireAdmin, handler);`,
    verify: 'Re-run SmartFuzz. Forced browsing should no longer appear.',
    ref: 'https://owasp.org/www-community/attacks/Forced_browsing',
  },
  sensitive_data_in_url: {
    what: 'Sensitive data (tokens, passwords) appeared in URL query parameters.',
    why: 'URLs are logged in server logs, browser history, and Referer headers.',
    steps: [
      'Pass sensitive data in request bodies (POST), not URL parameters.',
      'Use short-lived tokens for URL-based flows (password reset, email verification).',
    ],
    before: `GET /reset?token=supersecret123`,
    after: `POST /reset (token in request body)`,
    verify: 'Re-run SmartFuzz. Sensitive data in URL should no longer appear.',
    ref: 'https://owasp.org/Top10/A02_2021-Cryptographic_Failures/',
  },
  weak_tls: {
    what: 'The server supported weak TLS versions (TLS 1.0 or 1.1).',
    why: 'Weak TLS versions are vulnerable to downgrade attacks (POODLE, BEAST).',
    steps: [
      'Disable TLS 1.0 and 1.1; require TLS 1.2 minimum, prefer TLS 1.3.',
      'In nginx: ssl_protocols TLSv1.2 TLSv1.3;',
    ],
    before: `ssl_protocols TLSv1 TLSv1.1 TLSv1.2;`,
    after: `ssl_protocols TLSv1.2 TLSv1.3;`,
    verify: 'Re-run SmartFuzz. Weak TLS should no longer appear.',
    ref: 'https://owasp.org/www-project-transport-layer-security/',
  },
  xxe: {
    what: 'An XML parser processed user-supplied XML with external entity resolution enabled.',
    why: 'Attackers can read local files (/etc/passwd, config), perform SSRF, or cause denial of service (billion laughs).',
    steps: [
      'Disable DTDs and external entities in your XML parser — this is the single most effective fix.',
      'Node.js: avoid libxmljs with noent; use fast-xml-parser or disable entity expansion.',
      'Java: factory.setFeature("http://apache.org/xml/features/disallow-doctype-decl", true).',
      'PHP: libxml_disable_entity_loader(true) on older versions; modern libxml is safe by default.',
      'Prefer JSON over XML for untrusted input where possible.',
    ],
    before: `const doc = libxml.parseXml(req.body, { noent: true }); // entities expanded`,
    after: `const doc = libxml.parseXml(req.body, { noent: false, nonet: true, dtdload: false });`,
    verify: 'Re-run SmartFuzz. The XXE finding should no longer appear and file:// payloads should not be reflected.',
    ref: 'https://owasp.org/www-community/vulnerabilities/XML_External_Entity_(XXE)_Processing',
  },
  jwt_alg_none: {
    what: 'The server accepted a JWT whose header declared "alg":"none" (or an algorithm it should not trust), skipping signature verification.',
    why: 'Attackers can forge tokens for any user — including admins — and gain full authenticated access without knowing any secret.',
    steps: [
      'Explicitly pin the allowed algorithm(s) when verifying — never trust the alg in the token header.',
      'Reject "none" and reject algorithm switches (e.g. RS256 → HS256 confusion).',
      'jsonwebtoken: jwt.verify(token, key, { algorithms: ["RS256"] }).',
      'Rotate signing keys if you suspect tokens were forged.',
    ],
    before: `jwt.verify(token, secret); // accepts whatever alg the token claims`,
    after: `jwt.verify(token, secret, { algorithms: ['HS256'] }); // alg:none rejected`,
    verify: 'Re-run SmartFuzz. A token with alg:none should now return 401, not authenticated access.',
    ref: 'https://owasp.org/www-project-web-security-testing-guide/latest/4-Web_Application_Security_Testing/06-Session_Management_Testing/10-Testing_JSON_Web_Tokens',
  },
  crlf_injection: {
    what: 'User input containing carriage-return/line-feed (\\r\\n) characters was reflected into HTTP response headers.',
    why: 'Attackers can inject arbitrary headers, split the response, poison caches, or set malicious cookies (HTTP response splitting).',
    steps: [
      'Strip or reject CR (%0d) and LF (%0a) characters from any value placed in a response header.',
      'Use framework APIs that encode header values rather than building headers by string concatenation.',
      'Validate redirect/location values against an allowlist before setting them.',
    ],
    before: `res.setHeader('Location', req.query.next); // next = "/\\r\\nSet-Cookie: admin=1"`,
    after: `const next = String(req.query.next).replace(/[\\r\\n]/g, '');\nres.setHeader('Location', next);`,
    verify: 'Re-run SmartFuzz. Injected CRLF payloads should no longer appear as separate response headers.',
    ref: 'https://owasp.org/www-community/vulnerabilities/CRLF_Injection',
  },
  exposed_secret: {
    what: 'A secret credential (API key, database password, private key, or access token) was found hardcoded inside a publicly accessible JavaScript file.',
    why: 'Anyone who visits your site can read this secret in their browser dev tools and use it to access your external services, databases, or accounts — at your cost and under your identity.',
    steps: [
      'Rotate the exposed credential IMMEDIATELY — assume it is already compromised.',
      'Move the secret out of frontend JS into a backend-only environment variable (process.env / .env, never committed).',
      'If the key is needed by the browser, proxy the call through your own backend so the secret never reaches the client.',
      'Add secret scanning to CI (gitleaks / detect-secrets / GitHub secret scanning) and a pre-commit hook to stop the next leak.',
    ],
    before: `// frontend bundle — anyone can read this\nconst apiKey = "AIzaSyAbc123...";\nfetch(\`https://api.example.com?key=\${apiKey}\`);`,
    after: `// backend only — key stays on the server\nconst apiKey = process.env.GOOGLE_API_KEY;\n// frontend calls YOUR backend; the backend calls the external service`,
    verify: 'Rotate the key, redeploy, then re-run SmartFuzz — the secret should no longer appear in any JS file. Check provider logs for unauthorized use since first deploy.',
    ref: 'https://owasp.org/www-community/vulnerabilities/Use_of_hard-coded_credentials',
  },
};

/** Get the fix guide for a vuln type, or a generic fallback. */
export function getFixGuide(type) {
  return FIX_GUIDES[type] || {
    what: `A ${type} vulnerability was detected.`,
    why: 'This vulnerability may allow attackers to compromise the application.',
    steps: ['Review the OWASP guidance for this vulnerability type.'],
    before: '',
    after: '',
    verify: 'Re-run SmartFuzz after applying fixes.',
    ref: 'https://owasp.org/www-project-top-ten/',
  };
}
