// Sensitive paths checked by the Exposed Files Scanner (PRD §9.4). Our own data
// file (we ship no Nikto code/db). Each entry maps a path to the vuln type it
// represents when accessible, plus a severity hint via type. Grouped by risk.
//
// `type` MUST be a key in @smartfuzz/shared vulnTypes (findingFactory throws
// otherwise). `match` (optional) is a regex the response body must satisfy to
// reduce false positives on soft-404 pages.

export const SENSITIVE_PATHS = [
  // ── Critical: environment & secrets ──
  { path: '/.env', type: 'exposed_sensitive_file', desc: 'Environment file (credentials)' },
  { path: '/.env.local', type: 'exposed_sensitive_file', desc: 'Local environment file' },
  { path: '/.env.development', type: 'exposed_sensitive_file', desc: 'Dev environment file' },
  { path: '/.env.production', type: 'exposed_sensitive_file', desc: 'Production environment file' },
  { path: '/.env.staging', type: 'exposed_sensitive_file', desc: 'Staging environment file' },
  { path: '/.env.test', type: 'exposed_sensitive_file', desc: 'Test environment file' },
  { path: '/.env.backup', type: 'exposed_sensitive_file', desc: 'Backup environment file' },
  { path: '/.env.bak', type: 'exposed_sensitive_file', desc: 'Backup environment file' },
  { path: '/secrets.json', type: 'exposed_sensitive_file', desc: 'Secrets file' },
  { path: '/credentials.json', type: 'exposed_sensitive_file', desc: 'Credentials file' },
  { path: '/.aws/credentials', type: 'exposed_sensitive_file', desc: 'AWS credentials' },
  { path: '/.dockercfg', type: 'exposed_sensitive_file', desc: 'Docker registry credentials' },
  { path: '/.docker/config.json', type: 'exposed_sensitive_file', desc: 'Docker registry credentials' },
  { path: '/.netrc', type: 'exposed_sensitive_file', desc: 'netrc credentials' },
  { path: '/.npmrc', type: 'exposed_sensitive_file', desc: 'npm config (may hold tokens)' },
  { path: '/.pypirc', type: 'exposed_sensitive_file', desc: 'PyPI credentials' },

  // ── Critical: config files ──
  { path: '/config.json', type: 'exposed_sensitive_file', desc: 'Application config' },
  { path: '/config.yml', type: 'exposed_sensitive_file', desc: 'Application config (YAML)' },
  { path: '/config.yaml', type: 'exposed_sensitive_file', desc: 'Application config (YAML)' },
  { path: '/config.xml', type: 'exposed_sensitive_file', desc: 'Application config (XML)' },
  { path: '/configuration.json', type: 'exposed_sensitive_file', desc: 'Application configuration' },
  { path: '/settings.json', type: 'exposed_sensitive_file', desc: 'Settings file' },
  { path: '/settings.yml', type: 'exposed_sensitive_file', desc: 'Settings file (YAML)' },
  { path: '/application.properties', type: 'exposed_sensitive_file', desc: 'Spring properties' },
  { path: '/application.yml', type: 'exposed_sensitive_file', desc: 'Spring config (YAML)' },
  { path: '/appsettings.json', type: 'exposed_sensitive_file', desc: '.NET app settings' },
  { path: '/local.settings.json', type: 'exposed_sensitive_file', desc: 'Azure Functions local settings' },
  { path: '/config.php', type: 'exposed_sensitive_file', desc: 'PHP config (may hold secrets)' },
  { path: '/configuration.php', type: 'exposed_sensitive_file', desc: 'Joomla configuration' },
  { path: '/database.php', type: 'exposed_sensitive_file', desc: 'PHP DB config' },
  { path: '/db.php', type: 'exposed_sensitive_file', desc: 'PHP DB config' },
  { path: '/connect.php', type: 'exposed_sensitive_file', desc: 'PHP DB connection' },
  { path: '/web.config', type: 'exposed_sensitive_file', desc: 'IIS config' },
  { path: '/wp-config.php', type: 'exposed_sensitive_file', desc: 'WordPress config' },
  { path: '/wp-config.php.bak', type: 'exposed_sensitive_file', desc: 'WordPress config backup' },
  { path: '/wp-config-sample.php', type: 'predictable_resource', desc: 'WordPress sample config' },

  // ── Critical: source control ──
  { path: '/.git/HEAD', type: 'exposed_sensitive_file', desc: 'Git repository metadata', match: /^ref:|^[0-9a-f]{40}/ },
  { path: '/.git/config', type: 'exposed_sensitive_file', desc: 'Git config' },
  { path: '/.git/FETCH_HEAD', type: 'exposed_sensitive_file', desc: 'Git fetch metadata' },
  { path: '/.git/index', type: 'exposed_sensitive_file', desc: 'Git index' },
  { path: '/.git/packed-refs', type: 'exposed_sensitive_file', desc: 'Git packed refs' },
  { path: '/.git/refs/heads/main', type: 'exposed_sensitive_file', desc: 'Git main ref' },
  { path: '/.git/refs/heads/master', type: 'exposed_sensitive_file', desc: 'Git master ref' },
  { path: '/.git/logs/HEAD', type: 'exposed_sensitive_file', desc: 'Git reflog' },
  { path: '/.gitignore', type: 'predictable_resource', desc: 'Git ignore file' },
  { path: '/.gitmodules', type: 'predictable_resource', desc: 'Git submodules' },
  { path: '/.svn/entries', type: 'exposed_sensitive_file', desc: 'SVN entries' },
  { path: '/.svn/wc.db', type: 'exposed_sensitive_file', desc: 'SVN working copy DB' },
  { path: '/.hg/hgrc', type: 'exposed_sensitive_file', desc: 'Mercurial config' },
  { path: '/.bzr/branch/branch.conf', type: 'exposed_sensitive_file', desc: 'Bazaar config' },

  // ── Critical: certificates & keys ──
  { path: '/id_rsa', type: 'exposed_sensitive_file', desc: 'SSH private key' },
  { path: '/id_rsa.pub', type: 'predictable_resource', desc: 'SSH public key' },
  { path: '/id_dsa', type: 'exposed_sensitive_file', desc: 'SSH DSA private key' },
  { path: '/server.key', type: 'exposed_sensitive_file', desc: 'TLS private key' },
  { path: '/private.key', type: 'exposed_sensitive_file', desc: 'Private key' },
  { path: '/server.pem', type: 'exposed_sensitive_file', desc: 'PEM key/cert bundle' },
  { path: '/server.crt', type: 'predictable_resource', desc: 'TLS certificate' },
  { path: '/ssl.key', type: 'exposed_sensitive_file', desc: 'SSL private key' },
  { path: '/certificate.pem', type: 'predictable_resource', desc: 'Certificate' },
  { path: '/.htpasswd', type: 'exposed_sensitive_file', desc: 'HTTP auth credentials' },
  { path: '/.htaccess', type: 'exposed_sensitive_file', desc: 'Apache access config' },

  // ── Critical: backups & dumps ──
  { path: '/backup.sql', type: 'exposed_sensitive_file', desc: 'Database dump' },
  { path: '/backup.tar.gz', type: 'exposed_sensitive_file', desc: 'Backup archive' },
  { path: '/backup.tar', type: 'exposed_sensitive_file', desc: 'Backup archive' },
  { path: '/backup.zip', type: 'exposed_sensitive_file', desc: 'Backup archive' },
  { path: '/backup.bak', type: 'exposed_sensitive_file', desc: 'Backup file' },
  { path: '/backup.rar', type: 'exposed_sensitive_file', desc: 'Backup archive' },
  { path: '/db.sql', type: 'exposed_sensitive_file', desc: 'Database dump' },
  { path: '/database.sql', type: 'exposed_sensitive_file', desc: 'Database dump' },
  { path: '/dump.sql', type: 'exposed_sensitive_file', desc: 'Database dump' },
  { path: '/db.sqlite', type: 'exposed_sensitive_file', desc: 'SQLite database' },
  { path: '/database.sqlite', type: 'exposed_sensitive_file', desc: 'SQLite database' },
  { path: '/site.zip', type: 'exposed_sensitive_file', desc: 'Site archive' },
  { path: '/www.zip', type: 'exposed_sensitive_file', desc: 'Webroot archive' },
  { path: '/html.zip', type: 'exposed_sensitive_file', desc: 'HTML archive' },
  { path: '/public.zip', type: 'exposed_sensitive_file', desc: 'Public dir archive' },

  // ── High: admin / management panels ──
  { path: '/admin', type: 'exposed_admin_panel', desc: 'Admin panel' },
  { path: '/admin/', type: 'exposed_admin_panel', desc: 'Admin panel' },
  { path: '/admin/login', type: 'exposed_admin_panel', desc: 'Admin login' },
  { path: '/admin/dashboard', type: 'exposed_admin_panel', desc: 'Admin dashboard' },
  { path: '/administrator', type: 'exposed_admin_panel', desc: 'Admin panel' },
  { path: '/administrator/', type: 'exposed_admin_panel', desc: 'Admin panel' },
  { path: '/superadmin', type: 'exposed_admin_panel', desc: 'Super admin panel' },
  { path: '/wp-admin/', type: 'exposed_admin_panel', desc: 'WordPress admin' },
  { path: '/wp-login.php', type: 'exposed_admin_panel', desc: 'WordPress login' },
  { path: '/phpmyadmin/', type: 'exposed_admin_panel', desc: 'phpMyAdmin' },
  { path: '/pma/', type: 'exposed_admin_panel', desc: 'phpMyAdmin (alias)' },
  { path: '/adminer.php', type: 'exposed_admin_panel', desc: 'Adminer DB tool' },
  { path: '/adminer', type: 'exposed_admin_panel', desc: 'Adminer DB tool' },
  { path: '/manager/html', type: 'exposed_admin_panel', desc: 'Tomcat manager' },
  { path: '/manager/', type: 'exposed_admin_panel', desc: 'Management interface' },
  { path: '/management', type: 'exposed_admin_panel', desc: 'Management interface' },
  { path: '/controlpanel', type: 'exposed_admin_panel', desc: 'Control panel' },
  { path: '/cpanel', type: 'exposed_admin_panel', desc: 'cPanel' },
  { path: '/panel', type: 'exposed_admin_panel', desc: 'Admin panel' },
  { path: '/console', type: 'exposed_admin_panel', desc: 'H2/Rails console' },
  { path: '/backend', type: 'exposed_admin_panel', desc: 'Backend interface' },
  { path: '/backend/', type: 'exposed_admin_panel', desc: 'Backend interface' },
  { path: '/cms', type: 'exposed_admin_panel', desc: 'CMS interface' },
  { path: '/dashboard/admin', type: 'exposed_admin_panel', desc: 'Admin dashboard' },

  // ── High: Spring Boot actuator (secrets/env) ──
  { path: '/actuator', type: 'exposed_admin_panel', desc: 'Spring Boot actuator' },
  { path: '/actuator/env', type: 'exposed_sensitive_file', desc: 'Spring actuator env (secrets)' },
  { path: '/actuator/health', type: 'info_disclosure', desc: 'Spring actuator health' },
  { path: '/actuator/info', type: 'info_disclosure', desc: 'Spring actuator info' },
  { path: '/actuator/mappings', type: 'info_disclosure', desc: 'Spring actuator route map' },
  { path: '/actuator/beans', type: 'info_disclosure', desc: 'Spring actuator beans' },
  { path: '/actuator/configprops', type: 'exposed_sensitive_file', desc: 'Spring actuator config props' },
  { path: '/actuator/loggers', type: 'info_disclosure', desc: 'Spring actuator loggers' },
  { path: '/actuator/heapdump', type: 'exposed_sensitive_file', desc: 'Spring actuator heap dump' },
  { path: '/env', type: 'exposed_sensitive_file', desc: 'Spring env endpoint (legacy)' },
  { path: '/beans', type: 'info_disclosure', desc: 'Spring beans (legacy)' },
  { path: '/dump', type: 'exposed_sensitive_file', desc: 'Spring thread dump (legacy)' },
  { path: '/configprops', type: 'exposed_sensitive_file', desc: 'Spring config props (legacy)' },
  { path: '/shutdown', type: 'exposed_admin_panel', desc: 'Spring shutdown endpoint' },

  // ── Medium: API docs / specs ──
  { path: '/api-docs', type: 'predictable_resource', desc: 'API documentation' },
  { path: '/api/docs', type: 'predictable_resource', desc: 'API documentation' },
  { path: '/api/swagger', type: 'predictable_resource', desc: 'Swagger API docs' },
  { path: '/swagger.json', type: 'predictable_resource', desc: 'Swagger spec' },
  { path: '/swagger.yaml', type: 'predictable_resource', desc: 'Swagger spec (YAML)' },
  { path: '/swagger-ui', type: 'predictable_resource', desc: 'Swagger UI' },
  { path: '/swagger-ui.html', type: 'predictable_resource', desc: 'Swagger UI' },
  { path: '/openapi.json', type: 'predictable_resource', desc: 'OpenAPI spec' },
  { path: '/openapi.yaml', type: 'predictable_resource', desc: 'OpenAPI spec (YAML)' },
  { path: '/v1/api-docs', type: 'predictable_resource', desc: 'API docs (v1)' },
  { path: '/v2/api-docs', type: 'predictable_resource', desc: 'API docs (v2)' },
  { path: '/v3/api-docs', type: 'predictable_resource', desc: 'API docs (v3)' },
  { path: '/graphql', type: 'predictable_resource', desc: 'GraphQL endpoint' },
  { path: '/graphiql', type: 'predictable_resource', desc: 'GraphiQL IDE' },
  { path: '/playground', type: 'predictable_resource', desc: 'GraphQL playground' },
  { path: '/__graphql', type: 'predictable_resource', desc: 'GraphQL endpoint' },

  // ── Medium: server status / monitoring ──
  { path: '/server-status', type: 'info_disclosure', desc: 'Apache server-status' },
  { path: '/server-info', type: 'info_disclosure', desc: 'Apache server-info' },
  { path: '/status', type: 'info_disclosure', desc: 'Status endpoint' },
  { path: '/health', type: 'info_disclosure', desc: 'Health endpoint' },
  { path: '/healthz', type: 'info_disclosure', desc: 'Health endpoint (k8s)' },
  { path: '/metrics', type: 'info_disclosure', desc: 'Metrics endpoint (Prometheus)' },
  { path: '/stats', type: 'info_disclosure', desc: 'Statistics endpoint' },
  { path: '/trace', type: 'verbose_error', desc: 'Trace endpoint' },
  { path: '/_ah/admin', type: 'exposed_admin_panel', desc: 'App Engine admin' },

  // ── Medium: PHP info / debug ──
  { path: '/phpinfo.php', type: 'info_disclosure', desc: 'phpinfo()' },
  { path: '/info.php', type: 'info_disclosure', desc: 'phpinfo()' },
  { path: '/php_info.php', type: 'info_disclosure', desc: 'phpinfo()' },
  { path: '/test.php', type: 'predictable_resource', desc: 'PHP test file' },
  { path: '/phptest.php', type: 'predictable_resource', desc: 'PHP test file' },
  { path: '/debug.php', type: 'verbose_error', desc: 'PHP debug endpoint' },
  { path: '/debug', type: 'verbose_error', desc: 'Debug endpoint' },

  // ── Medium: dependency manifests ──
  { path: '/package.json', type: 'predictable_resource', desc: 'npm manifest (dependency versions)' },
  { path: '/package-lock.json', type: 'predictable_resource', desc: 'npm lockfile' },
  { path: '/yarn.lock', type: 'predictable_resource', desc: 'Yarn lockfile' },
  { path: '/composer.json', type: 'predictable_resource', desc: 'Composer manifest' },
  { path: '/composer.lock', type: 'predictable_resource', desc: 'Composer lockfile' },
  { path: '/requirements.txt', type: 'predictable_resource', desc: 'Python requirements' },
  { path: '/Pipfile', type: 'predictable_resource', desc: 'Python Pipfile' },
  { path: '/Pipfile.lock', type: 'predictable_resource', desc: 'Python Pipfile lock' },
  { path: '/Gemfile', type: 'predictable_resource', desc: 'Ruby Gemfile' },
  { path: '/Gemfile.lock', type: 'predictable_resource', desc: 'Ruby Gemfile lock' },
  { path: '/pom.xml', type: 'predictable_resource', desc: 'Maven manifest' },
  { path: '/build.gradle', type: 'predictable_resource', desc: 'Gradle build file' },
  { path: '/go.mod', type: 'predictable_resource', desc: 'Go modules manifest' },

  // ── Medium: framework-specific source ──
  { path: '/manage.py', type: 'predictable_resource', desc: 'Django manage script' },
  { path: '/wsgi.py', type: 'predictable_resource', desc: 'WSGI entrypoint' },
  { path: '/settings.py', type: 'exposed_sensitive_file', desc: 'Django settings (may hold SECRET_KEY)' },
  { path: '/local_settings.py', type: 'exposed_sensitive_file', desc: 'Django local settings' },
  { path: '/config/database.yml', type: 'exposed_sensitive_file', desc: 'Rails DB config' },
  { path: '/config/secrets.yml', type: 'exposed_sensitive_file', desc: 'Rails secrets' },
  { path: '/config/credentials.yml.enc', type: 'exposed_sensitive_file', desc: 'Rails encrypted credentials' },
  { path: '/WEB-INF/web.xml', type: 'exposed_sensitive_file', desc: 'Java web descriptor' },
  { path: '/WEB-INF/applicationContext.xml', type: 'exposed_sensitive_file', desc: 'Spring context' },
  { path: '/META-INF/MANIFEST.MF', type: 'info_disclosure', desc: 'JAR manifest' },
  { path: '/artisan', type: 'predictable_resource', desc: 'Laravel artisan script' },
  { path: '/storage/logs/laravel.log', type: 'exposed_sensitive_file', desc: 'Laravel log' },

  // ── Medium: CI / deploy / IaC ──
  { path: '/Dockerfile', type: 'predictable_resource', desc: 'Dockerfile' },
  { path: '/docker-compose.yml', type: 'exposed_sensitive_file', desc: 'Docker compose (may hold env)' },
  { path: '/.dockerignore', type: 'predictable_resource', desc: 'Docker ignore' },
  { path: '/.travis.yml', type: 'predictable_resource', desc: 'Travis CI config' },
  { path: '/Jenkinsfile', type: 'predictable_resource', desc: 'Jenkins pipeline' },
  { path: '/.circleci/config.yml', type: 'predictable_resource', desc: 'CircleCI config' },
  { path: '/.gitlab-ci.yml', type: 'predictable_resource', desc: 'GitLab CI config' },
  { path: '/terraform.tfvars', type: 'exposed_sensitive_file', desc: 'Terraform variables (secrets)' },
  { path: '/serverless.yml', type: 'exposed_sensitive_file', desc: 'Serverless config' },
  { path: '/cloudformation.json', type: 'predictable_resource', desc: 'CloudFormation template' },

  // ── Web server configs ──
  { path: '/nginx.conf', type: 'exposed_sensitive_file', desc: 'nginx config' },
  { path: '/httpd.conf', type: 'exposed_sensitive_file', desc: 'Apache config' },
  { path: '/apache.conf', type: 'exposed_sensitive_file', desc: 'Apache config' },

  // ── Logs ──
  { path: '/access.log', type: 'exposed_sensitive_file', desc: 'Access log' },
  { path: '/error.log', type: 'exposed_sensitive_file', desc: 'Error log' },
  { path: '/debug.log', type: 'exposed_sensitive_file', desc: 'Debug log' },
  { path: '/app.log', type: 'exposed_sensitive_file', desc: 'Application log' },
  { path: '/application.log', type: 'exposed_sensitive_file', desc: 'Application log' },
  { path: '/wp-content/debug.log', type: 'exposed_sensitive_file', desc: 'WordPress debug log' },

  // ── WordPress / CMS extras ──
  { path: '/wp-json/wp/v2/users', type: 'info_disclosure', desc: 'WP REST user enumeration' },
  { path: '/xmlrpc.php', type: 'exposed_admin_panel', desc: 'WordPress XML-RPC' },

  // ── Upload / listing-prone directories ──
  { path: '/uploads/', type: 'directory_listing', desc: 'Uploads directory' },
  { path: '/files/', type: 'directory_listing', desc: 'Files directory' },
  { path: '/backup/', type: 'directory_listing', desc: 'Backup directory' },
  { path: '/backups/', type: 'directory_listing', desc: 'Backups directory' },
  { path: '/logs/', type: 'directory_listing', desc: 'Logs directory' },
  { path: '/tmp/', type: 'directory_listing', desc: 'Temp directory' },

  // ── Informational: metadata & disclosure ──
  { path: '/.DS_Store', type: 'predictable_resource', desc: 'macOS directory metadata' },
  { path: '/Thumbs.db', type: 'predictable_resource', desc: 'Windows thumbnail cache' },
  { path: '/desktop.ini', type: 'predictable_resource', desc: 'Windows folder config' },
  { path: '/crossdomain.xml', type: 'info_disclosure', desc: 'Flash cross-domain policy' },
  { path: '/clientaccesspolicy.xml', type: 'info_disclosure', desc: 'Silverlight access policy' },
  { path: '/.well-known/security.txt', type: 'predictable_resource', desc: 'security.txt' },
  { path: '/robots.txt', type: 'predictable_resource', desc: 'robots.txt' },
  { path: '/sitemap.xml', type: 'predictable_resource', desc: 'sitemap.xml' },
  { path: '/CHANGELOG.md', type: 'info_disclosure', desc: 'Changelog (version disclosure)' },
  { path: '/VERSION', type: 'info_disclosure', desc: 'Version file' },
  { path: '/README.md', type: 'predictable_resource', desc: 'Readme file' },
];
